### ISSUE TITLE
[Bug]: test `TestCodeBlockChecker.test_check_yaml_returns_error_on_bad_code_block` fails

### ISSUE THREAD

**Issue by natsukium** [rstcheck/rstcheck-core#84] opened 2023-11-25 02:42 UTC
### To Dos

- [X] I tested with the [latest released version](https://github.com/rstcheck/rstcheck/releases/latest).

- [X] I have checked the [issues](https://github.com/rstcheck/rstcheck/issues) and think that this is not a duplicate.

- [X] I added a very descriptive title to this issue.

### Example Code (python)

```Python
# these are shell commands

git clone https://github.com/rstcheck/rstcheck-core
cd rstcheck-core
git checkout v1.2.0
pip install .[testing]
pytest tests/checker_test.py
```

### Relevant log output

```Shell
――――――――――――――――――――――――――――――――――――――――――――――――― TestCodeBlockChecker.test_check_yaml_returns_error_on_bad_code_block ――――――――――――――――――――――――――――――――――――――――――――――――――

        @staticmethod
        def test_check_yaml_returns_error_on_bad_code_block() -> None:
            """Test ``check_json`` returns error on bad code block."""
            source = """
    spam: ham
      eggs: ham
    """
            cb_checker = checker.CodeBlockChecker("<string>")
    
            result = list(cb_checker.check_yaml(source))
    
>           assert len(result) == 1
E           assert 0 == 1
E            +  where 0 = len([])

cb_checker = <rstcheck_core.checker.CodeBlockChecker object at 0x7f5eba098e10>
result     = []
source     = '\nspam: ham\n  eggs: ham\n'

tests/checker_test.py:836: AssertionError
```

### Description

I am not sure. Maybe this test expects an error but it does not handle the error.

### Operating System

Linux

### Python Version

3.11.5

### rstcheck Version

1.2.0

**Comment by Cielquan** [comment] 2024-01-12 16:41
Sorry for the late response. The issue flew under my radar.

The tested function is [here](https://github.com/rstcheck/rstcheck-core/blob/v1.2.0/src/rstcheck_core/checker.py#L684-L704). It is tried to parse the yaml source. All yaml errors are catched and converted into `LintError`s which are no exceptions but just a custom type. All the `LintError`s are printed by rstcheck at the end. So there are no errors to handle in the test.

The [CI run (ubuntu py 3.11)](https://github.com/rstcheck/rstcheck-core/actions/runs/6851278296/job/18627208557) just before the 1.2 release was green in all 6 cases. Will need to test on my local maschine, if I can reproduce your issue.

EDIT: fix GHA error in logs (was my browser)

**Comment by Cielquan** [comment] 2024-01-12 17:06
The issue is that the test runs even when pyyaml is not installed. Therefore it fails. I added a skip condition in the linked PR so this issue should be fixed.

Because the base test tox env always had pyyaml installed this issue was not discovered in CI. In the PR I also remove yaml from the base test env and added a new one for testing with pyyaml.

**Closed as completed** 2024-01-12 17:39 UTC
Labels: bug

**Comment by natsukium** [comment] 2024-01-13 00:54
Thank you!
