### ISSUE TITLE
[Bugfix]: Activate TOML support on py >= 3.11

### ISSUE THREAD

**Issue by fizyk** [rstcheck/rstcheck-core#47] opened 2023-07-12 10:55 UTC
### To Dos

- [X] I have checked the [issues](https://github.com/rstcheck/rstcheck/issues) and think that this is not a duplicate.

- [X] I added a very descriptive title to this issue.

### Description

If toml support is present (tomli intalled or python 3.11) in cases where directory is passed search for `.rstcheck.cfg | setup.cfg AND pyproject.toml` instead of only `.rstcheck.cfg | setup.cfg`

### Operating System

Linux

### Python Version

3.11.4

### rstcheck Version

6.1.2

**Comment by Cielquan** [comment] 2023-07-14 15:09
This should actually be the case. But I am currently not able to verify that it works as intended. Hopefully I will be able to check it out within the next 2 weeks, but no promise.

**Comment by Cielquan** [comment] 2023-07-26 07:38
I can partially confirm the issue. If tomli is installed the toml support is active. Python >= 3.11 does not trigger toml support.

**Comment by Cielquan** [comment] 2023-08-02 12:50
I will make a new release after the pydantic upgrade PR is merged.

**Closed as completed** 2023-08-02 12:49 UTC
Labels: feature
