### ISSUE TITLE
[Bug]: AttributeError when using `.. include::`

### ISSUE THREAD

**Issue by htgoebel** [rstcheck/rstcheck-core#95] opened 2024-03-17 21:58 UTC
### To Dos

- [X] I tested with the [latest released version](https://github.com/rstcheck/rstcheck/releases/latest).
- [X] I have checked the [issues](https://github.com/rstcheck/rstcheck/issues) and think that this is not a duplicate.
- [X] I added a very descriptive title to this issue.

### Example Code (rst)

```rst
This is the outer text.

.. include:: _common_definitions.txt
```

### Relevant log output

```Shell
WARNING:rstcheck_core.checker:An `AttributeError` error occured. 
This is most probably due to a code block directive (code/code-block/sourcecode)
without a specified language. This may result in a false negative for source: 'index.rst'.
The reason can also be another directive. For more information see the FAQ 
(https://rstcheck-core.rtfd.io/en/latest/faq) or the corresponding 
github issue: https://github.com/rstcheck/rstcheck-core/issues/3.
```

### Description

The file above is named `index.rst`. There is a second file (`_common_definitions.txt`):
```rst
This is some included text.
```

- running `rst2html5.py index.rst` works as expected: the output html contains the included text.
- running `rstcheck index.rst` gives the warning shown above.

Additionally:
- The warning is shown no matter whether the file exists or not.

### Operating System

Linux

### Python Version

3.10

### rstcheck Version

rstcheck CLI Version: 6.2.0 rstcheck-core Version: 1.2.0

**Comment by Cielquan** [comment] 2024-03-23 09:50
The issue is independent of the CLI so I moved the issue here.

The AttributeError is caused inside `sphinx` internal code. https://github.com/rstcheck/rstcheck-core/issues/3#issuecomment-1681934867 mentioned that this error can be caused from include directives, but it mostly occurs with language-less code-blocks as far as I know.
Unfortunately this issue is almost a decade old (https://github.com/rstcheck/rstcheck-core/issues/3#issuecomment-1140405059) and I don't have a fix for this. But I am open for PRs if you find a fix.

What wonders me in your case is, that you seem to use `rst2html5` and not `sphinx` for building you docs. The issue only occurs if `sphinx` is installed inside the venv from where you are running `rstcheck`. And when you install `rstcheck` it only installs `sphinx` too if you run something like `pip install rstcheck[sphinx]`. Therefore it could be a simple fix to remove `sphinx` if you do not use it.

Closing as duplicate/in favor of #3.

**Closed as not planned by Cielquan** 2024-03-23 09:50 UTC
Labels: bug

**Comment by htgoebel** [comment] 2024-03-23 13:11
Sorry, I missed that #3 also mentions include directives.

I'm using sphinx for building the docs. Above I just used rst2html5 to show/test that index.rst compiles fine when using just rst2x.

When not installing sphinx in the environment I get lots of "Unknown interpreted text role" and "Unknown directive type" errors. Thus this seems to not be the solution either :-/

**Comment by Cielquan** [comment] 2024-03-23 13:15
Ah ok. Yeah all those unknown things are then probably sphinx things which are not part of basic RST.
